const fs = require('fs');
const path = require('path');

const target = path.join(__dirname, '..', 'src', 'i18n', 'translations.js');
let content = fs.readFileSync(target, 'utf8');

const prizesI18n = {
    ar: "\n        pzDailySub: 'مسابقات يومية — تصفير كل 24 ساعة',\n        pzTabKillers: 'تصنيف القتلة', pzTabSurvivors: 'تصنيف الناجين', pzTabWallet: 'المحفظة',\n        pzCoin: 'عملة', pzResetIn: 'تصفير خلال', pzDailyPrize: 'الجائزة اليومية',\n        pzTopKillerHover: 'أعلى قاتل للوحوش يربح 5 عملات ذهبية', pzMonstersKilled: 'وحشاً قتلته اليوم',\n        pzRank: 'مرتبتك #', pzPlayerName: 'اللاعب', pzKillsScore: 'الوحوش المقتولة', pzPortalsKeys: 'البوابات / المفاتيح',\n        pzEmpty: 'لا يوجد لاعبون اليوم بعد — كن أول من يلعب! 🎮',\n        pzTenPortals: 'افتح 10 بوابات في يوم واحد → 10 عملات ذهبية', pzPortalsOpened: 'بوابة فتحتها اليوم',\n        pzHowItWorks: 'كيف تعمل؟', pzHide: 'إخفاء', pzHowToOpen: 'كيف تفتح بوابة؟',\n        pzHowToOpenDesc: 'اجمع 10 مفاتيح في المتاهة → ستظهر البوابة → ادخلها لتفوز.',\n        pzResetNote: 'في كل يوم يبدأ العد من صفر — المستوى والتقدم يتصفران يومياً.',\n        pzTenPortalsWin: 'من يفتح 10 بوابات في نفس اليوم يربح 10 عملات ذهبية مباشرة!',\n        pzProgressTitle: 'تقدمك نحو جائزة اليوم', pzPortalsOf10: 'بوابات', pzKeys: 'مفاتيح',\n        pzGoldBalance: 'عملة ذهبية ≈', pzHowToEarn: 'كيف تجمع العملات؟',\n        pzEarnKill: 'كن أعلى قاتل للوحوش يومياً → 5 عملات', pzEarnPortal: 'افتح 10 بوابات في يوم واحد → 10 عملات',\n        pzRateValue: 'سعر التحويل: 100 عملة = 1 دولار', pzWithdrawTitle: 'طلب سحب رصيدك',\n        pzWithdrawMin: 'الحد الأدنى للسحب: 500 عملة. أدخل معلومات التواصل وسيتم مراجعة طلبك يدوياً.',\n        pzWithdrawPlaceholder: 'اسمك الكامل\\nرقم WhatsApp أو البريد الإلكتروني\\nطريقة الاستلام',\n        pzWithdrawBtn: 'إرسال طلب السحب', pzWithdrawNeed: 'تحتاج {n} عملة إضافية للسحب',\n        pzWithdrawSuccess: '✅ تم إرسال طلب السحب! سيتواصل معك الفريق خلال 48 ساعة.'\n",
    en: "\n        pzDailySub: 'Daily Competitions — Resets every 24h',\n        pzTabKillers: 'Killers Leaderboard', pzTabSurvivors: 'Survivors Leaderboard', pzTabWallet: 'Wallet',\n        pzCoin: 'Coins', pzResetIn: 'Resets in', pzDailyPrize: 'Daily Prize',\n        pzTopKillerHover: 'Top monster killer wins 5 gold coins', pzMonstersKilled: 'Monsters killed today',\n        pzRank: 'Your Rank #', pzPlayerName: 'Player', pzKillsScore: 'Monsters Killed', pzPortalsKeys: 'Portals / Keys',\n        pzEmpty: 'No players yet today — be the first to play! 🎮',\n        pzTenPortals: 'Open 10 portals in one day → 10 gold coins', pzPortalsOpened: 'Portals opened today',\n        pzHowItWorks: 'How it works?', pzHide: 'Hide', pzHowToOpen: 'How to open a portal?',\n        pzHowToOpenDesc: 'Collect 10 keys in the maze → the portal will appear → enter to win.',\n        pzResetNote: 'Every day the count starts from zero — level and progress reset daily.',\n        pzTenPortalsWin: 'Opening 10 portals in the same day earns 10 gold coins instantly!',\n        pzProgressTitle: 'Progress towards today\\'s prize', pzPortalsOf10: 'portals', pzKeys: 'keys',\n        pzGoldBalance: 'Gold Coins ≈', pzHowToEarn: 'How to earn coins?',\n        pzEarnKill: 'Be the top monster killer daily → 5 coins', pzEarnPortal: 'Open 10 portals in one day → 10 coins',\n        pzRateValue: 'Exchange Rate: 100 coins = $1', pzWithdrawTitle: 'Withdraw Balance',\n        pzWithdrawMin: 'Minimum withdrawal: 500 coins. Enter contact info and your request will be reviewed.',\n        pzWithdrawPlaceholder: 'Full Name\\nWhatsApp or Email\\nPayment Method (PayPal, Bank...)',\n        pzWithdrawBtn: 'Submit Withdrawal Request', pzWithdrawNeed: 'Need {n} more coins to withdraw',\n        pzWithdrawSuccess: '✅ Withdrawal request sent! The team will contact you within 48 hours.'\n",
    de: "\n        pzDailySub: 'Tägliche Wettbewerbe — Zurückgesetzt alle 24 Std.',\n        pzTabKillers: 'Killer-Rangliste', pzTabSurvivors: 'Überlebenden-Rangliste', pzTabWallet: 'Brieftasche',\n        pzCoin: 'Münzen', pzResetIn: 'Zurückgesetzt in', pzDailyPrize: 'Täglicher Preis',\n        pzTopKillerHover: 'Der beste Monsterkiller gewinnt 5 Goldmünzen', pzMonstersKilled: 'Heute getötete Monster',\n        pzRank: 'Dein Rang #', pzPlayerName: 'Spieler', pzKillsScore: 'Getötete Monster', pzPortalsKeys: 'Portale / Schlüssel',\n        pzEmpty: 'Noch keine Spieler heute — sei der Erste! 🎮',\n        pzTenPortals: 'Öffne 10 Portale an einem Tag → 10 Goldmünzen', pzPortalsOpened: 'Heute geöffnete Portale',\n        pzHowItWorks: 'Wie funktioniert das?', pzHide: 'Verbergen', pzHowToOpen: 'Wie öffnet man ein Portal?',\n        pzHowToOpenDesc: 'Sammle 10 Schlüssel im Labyrinth → das Portal erscheint → tritt ein, um zu gewinnen.',\n        pzResetNote: 'Jeden Tag beginnt die Zählung bei Null — Fortschritt wird täglich zurückgesetzt.',\n        pzTenPortalsWin: 'Das Öffnen von 10 Portalen am selben Tag bringt sofort 10 Goldmünzen!',\n        pzProgressTitle: 'Fortschritt für den heutigen Preis', pzPortalsOf10: 'Portale', pzKeys: 'Schlüssel',\n        pzGoldBalance: 'Goldmünzen ≈', pzHowToEarn: 'Wie verdient man Münzen?',\n        pzEarnKill: 'Sei täglich der beste Monsterkiller → 5 Münzen', pzEarnPortal: 'Öffne 10 Portale an einem Tag → 10 Münzen',\n        pzRateValue: 'Wechselkurs: 100 Münzen = 1$', pzWithdrawTitle: 'Guthaben abheben',\n        pzWithdrawMin: 'Mindestauszahlung: 500 Münzen. Kontaktdaten eingeben und Anfrage wird geprüft.',\n        pzWithdrawPlaceholder: 'Vollständiger Name\\nWhatsApp oder E-Mail\\nZahlungsmethode (PayPal, Bank...)',\n        pzWithdrawBtn: 'Auszahlungsantrag senden', pzWithdrawNeed: 'Benötigt weitere {n} Münzen zur Auszahlung',\n        pzWithdrawSuccess: '✅ Auszahlungsantrag gesendet! Das Team kontaktiert dich innerhalb von 48 Stunden.'\n",
    fr: "\n        pzDailySub: 'Compétitions quotidiennes — Réinitialisation toutes les 24h',\n        pzTabKillers: 'Classement des Tueurs', pzTabSurvivors: 'Classement des Survivants', pzTabWallet: 'Portefeuille',\n        pzCoin: 'Pièces', pzResetIn: 'Réinitialisation dans', pzDailyPrize: 'Prix Quotidien',\n        pzTopKillerHover: 'Le meilleur tueur de monstres gagne 5 pièces d\\'or', pzMonstersKilled: 'Monstres tués aujourd\\'hui',\n        pzRank: 'Votre Rang #', pzPlayerName: 'Joueur', pzKillsScore: 'Monstres Tués', pzPortalsKeys: 'Portails / Clés',\n        pzEmpty: 'Aucun joueur aujourd\\'hui — soyez le premier à jouer ! 🎮',\n        pzTenPortals: 'Ouvrez 10 portails en un jour → 10 pièces d\\'or', pzPortalsOpened: 'Portails ouverts aujourd\\'hui',\n        pzHowItWorks: 'Comment ça marche ?', pzHide: 'Masquer', pzHowToOpen: 'Comment ouvrir un portail ?',\n        pzHowToOpenDesc: 'Collectez 10 clés dans le labyrinthe → le portail apparaîtra → entrez pour gagner.',\n        pzResetNote: 'Chaque jour, le compteur repart de zéro — progression réinitialisée quotidiennement.',\n        pzTenPortalsWin: 'Ouvrir 10 portails le même jour rapporte instantanément 10 pièces d\\'or !',\n        pzProgressTitle: 'Progression vers le prix d\\'aujourd\\'hui', pzPortalsOf10: 'portails', pzKeys: 'clés',\n        pzGoldBalance: 'Pièces d\\'Or ≈', pzHowToEarn: 'Comment gagner des pièces ?',\n        pzEarnKill: 'Soyez le meilleur tueur de monstres → 5 pièces', pzEarnPortal: 'Ouvrez 10 portails en un jour → 10 pièces',\n        pzRateValue: 'Taux de change : 100 pièces = 1$', pzWithdrawTitle: 'Retirer le solde',\n        pzWithdrawMin: 'Retrait minimum : 500 pièces. Entrez vos coordonnées pour examen de la demande.',\n        pzWithdrawPlaceholder: 'Nom Complet\\nWhatsApp ou Email\\nMéthode de paiement (PayPal, Banque...)',\n        pzWithdrawBtn: 'Soumettre la demande de retrait', pzWithdrawNeed: 'Il faut encore {n} pièces pour retirer',\n        pzWithdrawSuccess: '✅ Demande de retrait envoyée ! L\\'équipe vous contactera sous 48 heures.'\n",
    it: "\n        pzDailySub: 'Competizioni giornaliere — Ripristino ogni 24h',\n        pzTabKillers: 'Classifica Killer', pzTabSurvivors: 'Classifica Sopravvissuti', pzTabWallet: 'Portafoglio',\n        pzCoin: 'Monete', pzResetIn: 'Ripristino tra', pzDailyPrize: 'Premio Giornaliero',\n        pzTopKillerHover: 'Il miglior killer di mostri vince 5 monete d\\'oro', pzMonstersKilled: 'Mostri uccisi oggi',\n        pzRank: 'Il tuo grado #', pzPlayerName: 'Giocatore', pzKillsScore: 'Mostri Uccisi', pzPortalsKeys: 'Portali / Chiavi',\n        pzEmpty: 'Ancora nessun giocatore oggi — sii il primo a giocare! 🎮',\n        pzTenPortals: 'Apri 10 portali in un giorno → 10 monete d\\'oro', pzPortalsOpened: 'Portali aperti oggi',\n        pzHowItWorks: 'Come funziona?', pzHide: 'Nascondi', pzHowToOpen: 'Come si apre un portale?',\n        pzHowToOpenDesc: 'Raccogli 10 chiavi nel labirinto → apparirà il portale → entra per vincere.',\n        pzResetNote: 'Ogni giorno il conteggio riparte da zero — progressi azzerati ogni giorno.',\n        pzTenPortalsWin: 'Aprire 10 portali nello stesso giorno fa guadagnare 10 monete d\\'oro!',\n        pzProgressTitle: 'Progresso del premio di oggi', pzPortalsOf10: 'portali', pzKeys: 'chiavi',\n        pzGoldBalance: 'Monete d\\'Oro ≈', pzHowToEarn: 'Come guadagnare monete?',\n        pzEarnKill: 'Sii il miglior killer di mostri ogni giorno → 5 monete', pzEarnPortal: 'Apri 10 portali in un giorno → 10 monete',\n        pzRateValue: 'Tasso di Cambio: 100 monete = 1$', pzWithdrawTitle: 'Preleva Saldo',\n        pzWithdrawMin: 'Prelievo minimo: 500 monete. Inserisci info di contatto per la revisione.',\n        pzWithdrawPlaceholder: 'Nome Completo\\nWhatsApp o Email\\nMetodo di pagamento (PayPal, Banca...)',\n        pzWithdrawBtn: 'Invia Richiesta di Prelievo', pzWithdrawNeed: 'Servono altre {n} monete per prelevare',\n        pzWithdrawSuccess: '✅ Richiesta di prelievo inviata! Il team ti contatterà entro 48 ore.'\n",
    es: "\n        pzDailySub: 'Competiciones Diarias — Se reinicia cada 24h',\n        pzTabKillers: 'Clasificación de Asesinos', pzTabSurvivors: 'Clasificación de Supervivientes', pzTabWallet: 'Billetera',\n        pzCoin: 'Monedas', pzResetIn: 'Se reinicia en', pzDailyPrize: 'Premio Diario',\n        pzTopKillerHover: 'El mejor asesino de monstruos gana 5 monedas de oro', pzMonstersKilled: 'Monstruos asesinados hoy',\n        pzRank: 'Tu Rango #', pzPlayerName: 'Jugador', pzKillsScore: 'Monstruos Asesinados', pzPortalsKeys: 'Portales / Llaves',\n        pzEmpty: 'Aún no hay jugadores hoy — ¡sé el primero en jugar! 🎮',\n        pzTenPortals: 'Abre 10 portales en un día → 10 monedas de oro', pzPortalsOpened: 'Portales abiertos hoy',\n        pzHowItWorks: '¿Cómo funciona?', pzHide: 'Ocultar', pzHowToOpen: '¿Cómo abrir un portal?',\n        pzHowToOpenDesc: 'Recoge 10 llaves en el laberinto → aparecerá el portal → entra para ganar.',\n        pzResetNote: 'Cada día el conteo empieza desde cero — el progreso se reinicia diariamente.',\n        pzTenPortalsWin: '¡Abrir 10 portales en un mismo día otorga 10 monedas de oro al instante!',\n        pzProgressTitle: 'Progreso para el premio de hoy', pzPortalsOf10: 'portales', pzKeys: 'llaves',\n        pzGoldBalance: 'Monedas de Oro ≈', pzHowToEarn: '¿Cómo ganar monedas?',\n        pzEarnKill: 'Sé el mejor asesino de monstruos cada día → 5 monedas', pzEarnPortal: 'Abre 10 portales en un día → 10 monedas',\n        pzRateValue: 'Tasa de Cambio: 100 monedas = $1', pzWithdrawTitle: 'Retirar Saldo',\n        pzWithdrawMin: 'Retiro mínimo: 500 monedas. Ingresa información de contacto para revisión.',\n        pzWithdrawPlaceholder: 'Nombre Completo\\nWhatsApp o Correo Electrónico\\nMétodo de pago (PayPal, Banco...)',\n        pzWithdrawBtn: 'Enviar Solicitud de Retiro', pzWithdrawNeed: 'Faltan {n} monedas más para retirar',\n        pzWithdrawSuccess: '✅ ¡Solicitud de retiro enviada! El equipo te contactará dentro de 48 horas.'\n"
};

for (const lang of Object.keys(prizesI18n)) {
    const langStart = content.indexOf(lang + ': {');
    if (langStart === -1) continue;
    const endBraceMatch = content.indexOf('},', langStart);
    if (endBraceMatch > -1) {
       content = content.slice(0, endBraceMatch) + ',' + prizesI18n[lang] + content.slice(endBraceMatch);
    }
}

fs.writeFileSync(target, content, 'utf8');
